### PR TITLE
add in invalid command message

### PR DESCRIPTION
**Pull request by wrac4242**
Add an error response if a command is not valid

### CODE REVIEW

**Comment by promise** [comment]
https://github.com/meew0/discord-bot-best-practices
> 6. **Don't reply with "invalid command".** If a user uses a command that does not exist, then let it fail silently. Do not have it reply with something like "invalid command". Though if the command is correct, but arguments are wrong then it's okay to reply with "invalid args". If there is more than one bot in a server that shares a prefix, this can result in very obnoxious usage. If your bot's prefix is configurable, this rule can probably be safely disregarded.

although,
> If your bot's prefix is configurable, this rule can probably be safely disregarded.

I'll leave this open for discussion, I disagree with it but it might be more user friendly to add

**Comment by wrac4242** [comment]
One compromise could be having the message delete itself after a few seconds. However, the message delete time may be too short for some or too long

**Comment by lacuna-exe** [comment]
Imo a message might be a bit much, however a reaction with a red X labeled invalid-command would be a good compromise that showed the bot was responsive without being intrusive.

**Comment by wrac4242** [comment]
I sort of implemented your idea @e5510 by reacting to the message, however I did not label the reaction `invalid-command`, I just used the ❌ emoji

**Comment by wrac4242** [comment]
also going to convert this pr into a draft until a consensus can be formed

**Review by Ta1al — COMMENTED** [review]
I do not think it would be a good idea to respond (or react) to an invalid command. Most people can probably figure out they've spelt it wrong or the command simply does not exist.
`c!help` does show all the commands and `c!ping` is simple enough not to misspell to see if the bot is working.

**Comment by wrac4242** [comment]
@Aditya20-ai opinion?

**Comment by aditya20-b** [comment]
I don't think this feature is needed for a counting bot. Usually people setup the bot and then forget about it, only occasionally using the commands to set the count or to check the current count. Since the commands are not being actively used unlike other bots  this feature feels pointless, Besides reaction rate limits are strict in general and there might also be false positives.

**Comment by wrac4242** [comment]
> and there might also be false positives.

its placed in the code that checks the validity of the command

>  only occasionally using the commands to set the count or to check the current count

if they have issues using the commands, they may see it as being an issue with the bot instead of the command they are running

**Comment by aditya20-b** [comment]
> if they have issues using the commands, they may see it as being an issue with the bot instead of the command they are running

Honestly, So far I haven't seen any case like that while supporting users hence I'm not sure if people even have such an issue.


One of the main reasons I'm not a fan of this is a fact that countr is a "setup and forget about it" bot and commands wont be used regularly

**Comment by wrac4242** [comment]
out of the reviewers, 2/4 are actively against it, and the other two are sort of against it but want to see how others react to it
I am going to assume that this means it will not get merged then and closing the PR

**Comment by lacuna-exe** [comment]
As a side note, with it being a set and forget setup (commands that aren’t slash-utilized) however the user facing commands for checking the count and such mostly negate the need for an invalid command response as slash commands prevent typos for the most part.

**Pull request closed without merging**
