### PR TITLE
Remove Promise from .env.example

### PR DESCRIPTION
**Pull request by wrac4242**

### CODE REVIEW

**Comment by promise** [comment]
intended but discussable

**Comment by wrac4242** [comment]
If a person is self hosting, whether it is for testing purposes or for use, they wont usually need to have you as the admin

**Comment by wrac4242** [comment]
However, if it is to be set as the default, should I set it to be so in the config.ts?

**Comment by promise** [comment]
> However, if it is to be set as the default, should I set it to be so in the config.ts?

yeah that sounds like a better solution. Could you also unset ACCESS_ENABLED and BOT_SHARDS?

**Comment by wrac4242** [comment]
Just noticed my gitconfig has a misspelling, fixing now
edit: meaning it shows commits as unverified due to an email misspelling, it is now verified

**Pull request merged**
