### PR TITLE
Catch errors

### PR DESCRIPTION
**Pull request by Ta1al**

### CODE REVIEW

**Comment by fabianneufang** [comment]
Can there even be errors when restarting a shard?

**Comment by Ta1al** [comment]
> Can there even be errors when restarting a shard?

Yes, https://i.imgur.com/JgdXaPv.png

**Comment by fabianneufang** [comment]
Yeah I meant errors while restarting. Not because a shard was not found

**Comment by promise** [comment]
> Yeah I meant errors while restarting. Not because a shard was not found

Even if there was an error when restarting, this function only sends a message to the sharding manager to restart, it doesn't actually restart. So even if there was an error, it wouldn't really get picked up here as the command still sent the "respawn" message to the sharding manager successfully.

**Review by promise — APPROVED** [review]

**Pull request merged**
