### PR TITLE
Add support for emojis right after count

### LINKED ISSUE #229: When talking module is enabled allow people to talk after the number with a space
# Feature request

Basically just grab every character until you find a non-digit in the first word when looking for the count.

image

### PR DESCRIPTION
**Pull request by wrac4242**
resolves #229

### CODE REVIEW

**Comment by wrac4242** [comment]
I just realised this only works for custom emojis, one second

**Comment by wrac4242** [comment]
and its a fairly lazy system

**Comment by wrac4242** [comment]
This now should work with default and custom emojis, but it does it in a really basic way, where 123<message will be counted

**Comment by xhyrom** [comment]
Wouldn't it be better to just parse the numbers from the message?

**Comment by wrac4242** [comment]
due to how its currently set up in the code, and how promise wanted it in #229, this is the easiest way

**Comment by Ta1al** [comment]
> Wouldn't it be better to just parse the numbers from the message?

image
image

`parseInt()` would be an easier solution. But you'll also be able to send *non-counts* without a space:
image

**Comment by wrac4242** [comment]
That wouldn't be that hard to use, due to the current setup, that would be similar to the second step in my first commit. I am fine switching to that if promise is ok with it. I believe though It would require more error checking and handling.

**Comment by wrac4242** [comment]
@promise opinion?

**Comment by promise** [comment]
> @promise opinion?

if it works then it works ig. Not available this week but will look at it next week.

**Pull request merged**
