### PR TITLE
add content tag to the text send flow action

### LINKED ISSUE #123: Add more functionality to send message action in flows
# Feature request

Add a function to the message action in flows to allow to send the triggering messages contents
the functionality must also get ignored or filtered in some form if it triggers a regex filter 

this will be useful if you want to create a second channel where all triggers of a flow are sent, especially with the pin limit of 50

### PR DESCRIPTION
**Pull request by wrac4242**
feature request #123 
adds functionality to allow sending the messages contents inside the send message action
fixes #123

### CODE REVIEW

**Comment by promise** [comment]
I really like how you wanted something added, found out how to add it and then added it in this PR.

I unfortunately don't have a testing environment set up right now to test, it lgtm but would like someone to test first before merging.

**Comment by djohts** [comment]
i can test it rn, give me a few mins

**Comment by wrac4242** [comment]
makes sense to me, it is good to test it works first thats why i left it to lint before taking it out of draft

**Review by djohts — APPROVED** [review]
it does what it should; it works :D

**Pull request merged**
