### PR TITLE
refactor(src/sharding): use async/await

### PR DESCRIPTION
**Pull request by NotSugden**
*untested* just a little cleanup of the `updateBotInfo` function to make it a bit nicer to look at

### CODE REVIEW

**Comment by promise** [comment]
Does not work. There's something wrong with the broadcastEval function (as well as Shard#eval), hence why I'm using fetchClientValue.

If you get it working then feel free to open the PR again, but I'm stuck.

**Comment by NotSugden** [comment]
> Does not work. There's something wrong with the broadcastEval function (as well as Shard#eval), hence why I'm using fetchClientValue.
> 
> If you get it working then feel free to open the PR again, but I'm stuck.

late reply, but what exactly is going wrong? do you get an error or..? 

@promise

**Comment by promise** [comment]
No error, it just doesn't do anything. The broadcastEval-function doesn't resolve anything.

**Comment by NotSugden** [comment]
hm are you sure? perhaps open an issue on the `discordjs/discord.js` repo
for this

**Comment by NotSugden** [comment]
oh! i think i've found the issue in discord.js

**Comment by NotSugden** [comment]
@promise i've pushed a commit to this PR to fix the issue, can you re-open the PR?

**Comment by promise** [comment]
unfortunately, this PR is trying to merge with a deleted branch. Could you make a new PR? I'll take a look at it in the morning

**Pull request closed without merging**
