### PR TITLE
fix spelling mistake of multiplication to multiple

### PR DESCRIPTION
**Pull request by wrac4242**
replace use of 'multiplication' with 'multiple'
it just bothered me

### CODE REVIEW

**Comment by djohts** [comment]
I don't think it's a typo 👀

**Comment by wrac4242** [comment]
I think it is a typo, as `multiplication` is `the process or skill of multiplying.`
while `multiple` is `having or involving several parts, elements, or members.`
multiplication is a process, multiple is the result

**Comment by djohts** [comment]
well, @promise will say

**Comment by wrac4242** [comment]
(also it looks like my code editor automatically removed 2 trailing spaces)

**Comment by promise** [comment]
not a typo lol

**Comment by djohts** [comment]
👀

**Comment by lacuna-exe** [comment]
It would probably more grammatically correct if it was multiple, however multiplication probably gets the point across better.

> I think it is a typo, as `multiplication` is `the process or skill of multiplying.`
> while `multiple` is `having or involving several parts, elements, or members.`
> multiplication is a process, multiple is the result

**Pull request closed without merging**
