### PR TITLE
Create respawnshard command

### PR DESCRIPTION
**Pull request by promise**

### CODE REVIEW

**Review by fabianneufang — APPROVED** [review]

**Review by Ta1al — CHANGES_REQUESTED** [review]
Have a look at #95

**Review by aditya20-b — APPROVED** [review]

**Review by fabianneufang — COMMENTED** [review]
Why is error text in JS formatted?

**Review by fabianneufang — APPROVED** [review]
Better

**Comment by promise** [comment]
Can't be bothered waiting for the last two reviews. Not a huge PR anyways.

**Pull request merged**
