### PR TITLE
Fix issue in granting roles in Unique Role

### PR DESCRIPTION
**Pull request by wrac4242**
change order of granting and removing roles to ensure the role isn't granted, and then instantly removed

### CODE REVIEW

**Comment by promise** [comment]
if the concern here is that it's removing the role and then giving the role back to the same person then there should be a check implemented instead

**Comment by wrac4242** [comment]
concern is not that, its that i believe it gets added, and then removed right after

**Comment by promise** [comment]
wouldn't filtering `previousUserIds` work though? filtering as in filter out the user that triggered the flow

**Comment by wrac4242** [comment]
That is currently not implemented in the code I believe, this is the way I know how to do, and was the simplest to implement without making any changes to what each line does

**Comment by wrac4242** [comment]
closing PR on request of Promise

**Pull request closed without merging**
